// Platos de ejemplo: se siembran en la base de datos la primera vez,
// y sirven de carta de demostración mientras no hay base de datos conectada.
export const SEED = [
  {
    id: 1,
    titulo: 'Paella valenciana tradicional',
    slug: 'paella-valenciana-tradicional',
    categoria: 'arroces',
    descripcion: 'La de la terreta, con pollo, conejo, garrofó y bajoqueta. Fuego de leña si puede ser, y el arroz en su punto: seco, suelto y con socarraet.',
    tiempo_min: 90,
    comensales: 4,
    foto: '/assets/img/platos/paella.webp',
    destacada: 1,
  },
  {
    id: 2,
    titulo: 'Fideuà de Gandia',
    slug: 'fideua-de-gandia',
    categoria: 'arroces',
    descripcion: 'El plato marinero de la Safor: fideo fino dorado, fumet potente de morralla y ese alioli casero que no puede faltar en la mesa.',
    tiempo_min: 60,
    comensales: 4,
    foto: '/assets/img/platos/fideua.webp',
    destacada: 1,
  },
  {
    id: 3,
    titulo: 'Esgarraet amb mullaor',
    slug: 'esgarraet-amb-mullaor',
    categoria: 'entrantes',
    descripcion: 'Pimiento rojo asado desgarrado a mano con bacalao, ajo y un buen aceite. Frío, sencillo y absolutamente adictivo con pan tostado.',
    tiempo_min: 20,
    comensales: 6,
    foto: '/assets/img/platos/esgarraet.webp',
    destacada: 0,
  },
  {
    id: 4,
    titulo: "All i pebre d'anguila",
    slug: 'all-i-pebre-d-anguila',
    categoria: 'principal',
    descripcion: 'El guiso de la Albufera: anguila, ajo, pimentón y patata en un caldo corto ligado con almendra picada. Cocina de barraca en estado puro.',
    tiempo_min: 50,
    comensales: 4,
    foto: '/assets/img/platos/allipebre.webp',
    destacada: 0,
  },
  {
    id: 5,
    titulo: 'Arròs al forn',
    slug: 'arros-al-forn',
    categoria: 'arroces',
    descripcion: 'El arroz de cazuela de barro: costilla, morcilla, garbanzos, patata y una cabeza de ajos en el centro presidiendo. Del horno a tu mesa.',
    tiempo_min: 75,
    comensales: 4,
    foto: '/assets/img/platos/arrosalforn.webp',
    destacada: 0,
  },
  {
    id: 6,
    titulo: 'Coca de llanda',
    slug: 'coca-de-llanda',
    categoria: 'dulces',
    descripcion: 'El bizcocho valenciano de toda la vida, esponjoso y humilde, con su azúcar y canela por encima. En llanda, como manda la tradición.',
    tiempo_min: 50,
    comensales: 8,
    foto: '/assets/img/platos/coca.webp',
    destacada: 0,
  },
  {
    id: 7,
    titulo: 'Horchata de chufa y fartons',
    slug: 'horchata-de-chufa-y-fartons',
    categoria: 'bebidas',
    descripcion: 'Chufa de Alboraia, agua y el punto justo de dulce. Y para acompañar, fartons esponjosos para sucar hasta el fondo del vaso.',
    tiempo_min: 30,
    comensales: 4,
    foto: '/assets/img/platos/horchata.webp',
    destacada: 1,
  },
];
