// Platos de ejemplo: se siembran en la base de datos la primera vez,
// y sirven de carta de demostración mientras no hay base de datos conectada.
export const SEED = [
  {
    id: 1,
    titulo: 'Paella valenciana tradicional',
    slug: 'paella-valenciana-tradicional',
    categoria: 'arroces',
    descripcion: 'La de la terreta, con pollo, conejo, garrofó y bajoqueta. Fuego de leña si puede ser, y el arroz en su punto: seco, suelto y con socarraet.',
    ingredientes: 'Arroz redondo de la Albufera\nPollo y conejo de corral\nBajoqueta y garrofó frescos\nTomate de la huerta\nAzafrán en hebra y pimentón dulce\nRomero fresco y aceite de oliva virgen extra',
    consejo: 'La paella se cocina delante de vosotros y se lleva a la mesa en su hierro, con la ramita de romero coronando. El socarraet se reparte con justicia.',
    tiempo_min: 90,
    comensales: 4,
    foto: '/assets/img/platos/paella.webp',
    destacada: 1,
  },
  {
    id: 2,
    titulo: 'Fideuà de Gandia',
    slug: 'fideua-de-gandia',
    categoria: 'arroces',
    descripcion: 'El plato marinero de la Safor: fideo fino dorado, fumet potente de morralla y ese alioli casero que no puede faltar en la mesa.',
    ingredientes: 'Fideo fino tostado\nGamba de la lonja\nRape o sepia del día\nFumet de morralla hecho en casa\nÑoras y tomate maduro\nAlioli montado a mano',
    consejo: 'El fideo se tuesta en seco antes de mojarlo: cambia por completo el sabor. Y el alioli se monta en tu cocina, delante de quien quiera mirar.',
    tiempo_min: 60,
    comensales: 4,
    foto: '/assets/img/platos/fideua.webp',
    destacada: 1,
  },
  {
    id: 3,
    titulo: 'Esgarraet amb mullaor',
    slug: 'esgarraet-amb-mullaor',
    categoria: 'entrantes',
    descripcion: 'Pimiento rojo asado desgarrado a mano con bacalao, ajo y un buen aceite. Frío, sencillo y absolutamente adictivo con pan tostado.',
    ingredientes: 'Pimiento rojo asado al horno\nBacalao salado desmigado\nAjo laminado\nAceite de oliva virgen extra generoso\nPan de leña tostado para el mullaor',
    consejo: 'Se prepara la víspera para que el aceite se impregne del asado y del bacalao. El mullaor —mojar pan hasta acabar el aceite— es obligatorio.',
    tiempo_min: 20,
    comensales: 6,
    foto: '/assets/img/platos/esgarraet.webp',
    destacada: 0,
  },
  {
    id: 4,
    titulo: "All i pebre d'anguila",
    slug: 'all-i-pebre-d-anguila',
    categoria: 'principal',
    descripcion: 'El guiso de la Albufera: anguila, ajo, pimentón y patata en un caldo corto ligado con almendra picada. Cocina de barraca en estado puro.',
    ingredientes: 'Anguila de la Albufera\nAjos y pimentón de la Vera\nPatata chascada\nAlmendra frita y pan para el majado\nGuindilla al gusto',
    consejo: 'Si la anguila impone, se borda igual con rape o con sepia. El caldo se liga moviendo la cazuela en vaivén, nunca con cuchara.',
    tiempo_min: 50,
    comensales: 4,
    foto: '/assets/img/platos/allipebre.webp',
    destacada: 0,
  },
  {
    id: 5,
    titulo: 'Arròs al forn',
    slug: 'arros-al-forn',
    categoria: 'arroces',
    descripcion: 'El arroz de cazuela de barro: costilla, morcilla, garbanzos, patata y una cabeza de ajos en el centro presidiendo. Del horno a tu mesa.',
    ingredientes: 'Arroz redondo\nCaldo de puchero casero\nCostilla de cerdo y morcilla de cebolla\nGarbanzos, patata y tomate\nCabeza de ajos entera y azafrán',
    consejo: 'Se hornea en tu propia cocina y la cazuela de barro va directa a la mesa, crepitando. La cabeza de ajos del centro se la queda quien más la defienda.',
    tiempo_min: 75,
    comensales: 4,
    foto: '/assets/img/platos/arrosalforn.webp',
    destacada: 0,
  },
  {
    id: 6,
    titulo: 'Coca de llanda',
    slug: 'coca-de-llanda',
    categoria: 'dulces',
    descripcion: 'El bizcocho valenciano de toda la vida, esponjoso y humilde, con su azúcar y canela por encima. En llanda, como manda la tradición.',
    ingredientes: 'Huevos de corral\nHarina floja y gaseosas de papelillos\nLeche y aceite suave\nRalladura de limón\nAzúcar y canela para la costra',
    consejo: 'Sale del horno templada, cortada en cuadrados dentro de la propia llanda. Con un vaso de mistela o de horchata, la merienda está resuelta.',
    tiempo_min: 50,
    comensales: 8,
    foto: '/assets/img/platos/coca.webp',
    destacada: 0,
  },
  {
    id: 7,
    titulo: 'Horchata de chufa y fartons',
    slug: 'horchata-de-chufa-y-fartons',
    categoria: 'bebidas',
    descripcion: 'Chufa de Alboraia, agua y el punto justo de dulce. Y para acompañar, fartons esponjosos para sucar hasta el fondo del vaso.',
    ingredientes: 'Chufa seca de Alboraia con D.O.\nAgua fría y azúcar al gusto\nCanela y piel de limón\nFartons artesanos recién hechos',
    consejo: 'Se sirve casi al hielo, recién colada, sin conservantes: es un producto vivo que se hace el mismo día. A sucar sin vergüenza.',
    tiempo_min: 30,
    comensales: 4,
    foto: '/assets/img/platos/horchata.webp',
    destacada: 1,
  },
];
