// Platos de ejemplo: se siembran en la base de datos la primera vez,
// y sirven de carta de demostración mientras no hay base de datos conectada.
export const SEED = [
  {
    id: 1,
    titulo: 'Paella valenciana tradicional',
    slug: 'paella-valenciana-tradicional',
    categoria: 'carnes',
    descripcion: 'La de la terreta, con pollo, conejo, garrofó y bajoqueta. Fuego de leña si puede ser, y el arroz en su punto: seco, suelto y con socarraet.',
    ingredientes: 'Arroz, pollo, conejo, garrofó, bajoqueta, tomate, pimentón, azafrán, aceite de oliva, romero',
    tiempo_min: 90,
    comensales: 4,
    foto: '/assets/img/platos/paella.webp',
    destacada: 1,
  },
  {
    id: 2,
    titulo: 'Fideuà de Gandia',
    slug: 'fideua-de-gandia',
    categoria: 'pescados',
    descripcion: 'El plato marinero de la Safor: fideo fino dorado, fumet potente de morralla y ese alioli casero que no puede faltar en la mesa.',
    ingredientes: 'Fideo, sepia, gambas, pescado de roca, tomate, pimentón, azafrán, ajo, aceite de oliva',
    tiempo_min: 60,
    comensales: 4,
    foto: '/assets/img/platos/fideua.webp',
    destacada: 1,
  },
  {
    id: 3,
    titulo: 'Esgarraet amb mullaor',
    slug: 'esgarraet-amb-mullaor',
    categoria: 'ensaladas',
    descripcion: 'Pimiento rojo asado desgarrado a mano con bacalao, ajo y un buen aceite. Frío, sencillo y absolutamente adictivo con pan tostado.',
    ingredientes: 'Pimiento rojo asado, bacalao, ajo, aceite de oliva virgen extra, sal',
    tiempo_min: 20,
    comensales: 6,
    foto: '/assets/img/platos/esgarraet.webp',
    destacada: 0,
  },
  {
    id: 4,
    titulo: "All i pebre d'anguila",
    slug: 'all-i-pebre-d-anguila',
    categoria: 'pescados',
    descripcion: 'El guiso de la Albufera: anguila, ajo, pimentón y patata en un caldo corto ligado con almendra picada. Cocina de barraca en estado puro.',
    ingredientes: 'Anguila, patata, ajo, pimentón, almendra, guindilla, aceite de oliva',
    tiempo_min: 50,
    comensales: 4,
    foto: '/assets/img/platos/allipebre.webp',
    destacada: 0,
  },
  {
    id: 5,
    titulo: 'Arròs al forn',
    slug: 'arros-al-forn',
    categoria: 'legumbres',
    descripcion: 'El arroz de cazuela de barro: costilla, morcilla, garbanzos, patata y una cabeza de ajos en el centro presidiendo. Del horno a tu mesa.',
    ingredientes: 'Arroz, costilla de cerdo, morcilla, garbanzos, patata, tomate, cabeza de ajos, pimentón',
    tiempo_min: 75,
    comensales: 4,
    foto: '/assets/img/platos/arrosalforn.webp',
    destacada: 0,
  },
  {
    id: 6,
    titulo: 'Coca de llanda',
    slug: 'coca-de-llanda',
    categoria: 'dulces',
    descripcion: 'El bizcocho valenciano de toda la vida, esponjoso y humilde, con su azúcar y canela por encima. En llanda, como manda la tradición.',
    ingredientes: 'Harina, huevo, azúcar, aceite de oliva suave, leche, ralladura de limón, canela',
    tiempo_min: 50,
    comensales: 8,
    foto: '/assets/img/platos/coca.webp',
    destacada: 0,
  },
  {
    id: 7,
    titulo: 'Crema de calabaza asada',
    slug: 'crema-de-calabaza-asada',
    categoria: 'cremas',
    descripcion: 'Calabaza del huerto asada lentamente hasta caramelizar, con un hilo de aceite y un punto de jengibre. Aterciopelada y reconfortante.',
    ingredientes: 'Calabaza, puerro, cebolla, patata, jengibre, aceite de oliva, pipas de calabaza',
    tiempo_min: 40,
    comensales: 4,
    foto: '/assets/img/platos/horchata.webp',
    destacada: 0,
  },
];
